### ISSUE TITLE
Suggestion: Notification sound

### ISSUE THREAD

**Issue by nezayy** [geniiii/patcher#17]
Is it possible to put some sound to play when you receive notification or ping?

**Comment by geniiii** [comment]
Better suited for [ripcord-audio-hook](https://github.com/geniiii/ripcord-audio-hook), or an entirely separate project.
I'll consider it, since I (naively) assume it shouldn't be too much of a pain.

**Comment by geniiii** [comment]
I doubt you care about this anymore as it's been over a year since this issue was opened, but [u130b8's fork of ripcord-audio-hook](https://github.com/u130b8/ripcord-audio-hook/releases/tag/v1.5-notification-sounds) provides this functionality.
I'll be closing this issue since I don't think I'm going to be integrating it into either project.
